name: votrr
description: A biometric-enabled voting application prototype.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Navigation
  go_router: ^14.0.0

  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0

  # Biometrics & Device
  local_auth: ^2.3.0
  device_info_plus: ^10.0.0  
  flutter_secure_storage: ^9.2.2

  # UI
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.1

  # face detection
  google_mlkit_face_detection: ^0.11.0
  camera: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.0
  freezed: ^2.5.0
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#008751"
  adaptive_icon_foreground: "assets/images/logo.png"
  min_sdk_android: 23

flutter_native_splash:
  color: "#008751"
  image: assets/images/logo.png
  color_dark: "#005C36"
  image_dark: assets/images/logo.png
  android_12:
    color: "#008751"
    icon_background_color: "#008751"
    image: assets/images/logo.png
    color_dark: "#005C36"
    icon_background_color_dark: "#005C36"
    image_dark: assets/images/logo.png